### ISSUE TITLE
Wrong units displayed as app badge

### ISSUE THREAD

**Issue by derivadow** [nightscout/nightguard#120] opened 2020-09-28 08:33 UTC
The app badge is displaying data as mg/dL for mmol/L users. 

The app badge data is also displaying when high (?on transition to high) even if option disabled in the app.

**Comment by dhermanns** [comment] 2020-09-28 09:48
Thanks for your feedback. The latter should be a duplicate of #77.

**Comment by dhermanns** [comment] 2020-09-28 14:31
And mmol should be displayed now fine with the upcoming Testflight version.

**Closed by dhermanns** 2020-09-28 14:31 UTC
