### ISSUE TITLE
Crash after update to version 3

### ISSUE THREAD

**Issue by AlessioRosi** [nightscout/nightguard#112] opened 2020-09-10 17:22 UTC
I updated the app to the last version ( version 3) released yesterday. From that moment on the app crash on my iPhone and on my iPad.
Is this my issue or an app issue?

Thanks for your help

**Comment by dhermanns** [comment] 2020-09-10 17:32
Hi Alessio!

You could send me your Uri and I will have a look.

Maybe a reinstall of the app could help.

>
>

**Comment by Reddyzinho** [comment] 2020-09-10 17:36
I’m having the same problem. Just after I put the link ... it crashes. I have deleted and reinstall the app. The same thing. On the watch is the same problem ...

**Comment by dhermanns** [comment] 2020-09-10 18:29
Ok - think I found it. V3.0.1 should clean that out.

**Comment by LJK143** [comment] 2020-09-10 18:37
I also have the same on my iPhone 8 & sons IPhone SE 2020 since version 3.0.0 but our URL worked on friends Nightguard version she’s on version 2.8.0

**Comment by dhermanns** [comment] 2020-09-10 18:48
Chances are good that this is the same root cause. I will post the
TestFlight Link as soon as Apple cleared it.

**Comment by dhermanns** [comment] 2020-09-10 19:19
Testflight Version 3.0.1 should be available soon here:

https://testflight.apple.com/join/Ub8WcpcE

**Comment by Reddyzinho** [comment] 2020-09-10 19:21
Thanks :) 


Atentamente,

Tiago Cunha

No dia 10/09/2020, às 20:20, dhermanns <notifications@github.com> escreveu:

﻿
Testflight Version 3.0.1 should be available soon here:

https://testflight.apple.com/join/Ub8WcpcE

**Comment by Reddyzinho** [comment] 2020-09-10 19:31
Hello again. Isn’t fixed with the test flight app :( sorry ..... crash suddenly. I have sent you a report from iOS Test flight app. 


Atentamente,

Tiago Cunha

No dia 10/09/2020, às 20:20, dhermanns <notifications@github.com> escreveu:

﻿
Testflight Version 3.0.1 should be available soon here:

https://testflight.apple.com/join/Ub8WcpcE

**Comment by LJK143** [comment] 2020-09-11 04:06
Thank you 3.0.1 is working for us.

**Comment by dhermanns** [comment] 2020-09-11 04:45
Can you reproduce this? Your backend works fine with my clients here.

Tiago Cunha <notifications@github.com> schrieb am Do. 10. Sept. 2020 um
21:31:

**Comment by AlessioRosi** [comment] 2020-09-11 06:29
> Hi Alessio! You could send me your Uri and I will have a look. Maybe a reinstall of the app could help.
> […](#)

Dear dhermanns

i already reinstalled the app several times on both devices (Iphone & Ipad), but it doesent works :-(

I see your post about the crash if babaslrate is nil. This morning (my basalrate is NOT null) i try to reinstall the app, but .... nothing to do :(  the app crash again

I don't think could be a issue with the backend: the app works up to the last version and i use other apps with the same backend (AAPS, xDrip) on my android and DIY devices.

If it can help i can send you my backend URI

Thanks again for your help

**Comment by AlessioRosi** [comment] 2020-09-11 06:36
I installed the new beta by Testflight .... and it seems to work !!!!! :)

I will test today and i will give you my feedback

**Comment by dhermanns** [comment] 2020-09-11 08:44
Sounds good!

**Comment by maryannep** [comment] 2020-09-12 03:43
Thanks devs. Just updated to 3.0.1 and working well today!

**Comment by jetcrabs** [comment] 2020-09-12 06:17
at the first many thanks for Nightguard, I’ve used it for years, but i always had a little bump because a don’t have a little trend arrow on my iPhone and watch. Even more disturbing since last update 3.0.1 it appear an question tag instead od BG delta, what should i do? i tried to modify Config Var in Heroku, in option ENABLE i even wrote “delta” but there is no change.

**Comment by dhermanns** [comment] 2020-09-12 06:18
Thanks for your feedback Mary Anne!

**Comment by ntiliakos** [comment] 2020-09-12 06:32
Hi. Since the last update to version 3.0.1.590 there is no trend above the arrow beside the blood sugar. Your app is great has the best alarms.  I would like to ask you also about the care tab. When I try to set a temporary target I am getting an error that I don't have write access to the Nightscout site. Did you enter a security token in your Nightscout base URI? Which is the setting that I should change?

**Comment by dhermanns** [comment] 2020-09-12 07:05
Hi! Try 3.0.2 which is on TestFlight now:
https://testflight.apple.com/join/Ub8WcpcE


For the Care Tab to work you need to generate and attach a security token
to your Nightscout Url.

Have a look here:
http://www.nightscout.info/wiki/welcome/website-features/0-9-features/authentication-roles

The token must have assigned the role „careportal“.

Cu

**Comment by jetcrabs** [comment] 2020-09-12 07:30
V3.0.2.591 it appears see attached photo
![EC4C30F9-6C36-444A-B8A2-5AD1A642BAD7](https://user-images.githubusercontent.com/22548689/92990194-9babd900-f4da-11ea-926b-36d1701fbc70.jpeg)

**Comment by jetcrabs** [comment] 2020-09-12 07:32
I was iP 11Pro with 13.7 and AW4 44
![6F52668B-468F-4567-AC1D-F2B6663ECE6D](https://user-images.githubusercontent.com/22548689/92990215-d0b82b80-f4da-11ea-9137-10bb165f0854.png)

**Comment by jetcrabs** [comment] 2020-09-12 07:36
But how can I use param “direction” in config var to see the trend arrows , when BG is over +/-8 i see down arrow and up but when its lower there is only a dash

**Comment by jetcrabs** [comment] 2020-09-12 07:43
When its refreshing on watch it can be seen the time is jumping

**Comment by dhermanns** [comment] 2020-09-12 07:54
Not sure what you mean.

**Comment by jetcrabs** [comment] 2020-09-12 08:08
https://www.dropbox.com/s/mnnrvl0kuhkdcbf/IMG_2998.mov?dl=0

**Comment by dhermanns** [comment] 2020-09-12 08:23
Must be something that is unique to your backend or settings. For me the
arrow is fine even for small deltas:


You could leave me your Url:
ns.hermanns@spamgourmet.com

and I will have a look...

**Comment by jetcrabs** [comment] 2020-09-12 09:04
I’ve sent it you a few minutes ago

**Comment by dhermanns** [comment] 2020-09-12 10:18
The crash is fixed with V3.0.1 which is available in the app store now.

**Closed by dhermanns** 2020-09-12 10:18 UTC
Labels: bug
