### ISSUE TITLE
Bg change ”+/- 1” shown as ”+/- 0.1” since nov 2020

### ISSUE THREAD

**Issue by Samhagberth** [nightscout/nightguard#153] opened 2021-06-22 20:13 UTC

**Comment by Samhagberth** [comment] 2021-06-22 20:16
This fault has been there for many versions  
Since at least november 2020.

**Comment by dhermanns** [comment] 2021-06-22 20:20
Hi! Could you provide some more information about your system setup?

**Comment by Samhagberth** [comment] 2021-06-22 21:00
I have iPhone SE 2020 iOS 14,3 the same issue on my girlfriens IPhone 11 PRO

I have libre miaomiao and xdrip4ios sending to nightscout 14.0.6 (that shows the right bg change)

Best regards Sam Hagberth

**Comment by dhermanns** [comment] 2021-06-22 21:18
I guess you have your Nightscout backend configured to mmol?

**Comment by Samhagberth** [comment] 2021-06-22 21:22
Yes

/Sam Hagberth

**Comment by dhermanns** [comment] 2021-06-23 09:27
You could leave me your URI here: issue153.hermanns@spamgourmet.com.
Always hard to reproduce otherwise, since I'm using mgdl myself.

**Comment by Samhagberth** [comment] 2021-06-23 16:56
What do you mean by URI

Best regards  Sam Hagberth

**Comment by dhermanns** [comment] 2021-06-23 18:06
The link to your nightscout backend.

Samhagberth ***@***.***> schrieb am Mi. 23. Juni 2021 um
18:56:

**Comment by dhermanns** [comment] 2021-06-24 11:42
I was able to reproduce this. So it should be fixable...

**Comment by Samhagberth** [comment] 2021-06-24 12:40
Thank you !

Sam Hagberth

**Comment by dhermanns** [comment] 2021-06-24 20:02
Welcome! This goes back to a nightscout bug in the nightspot backend. But it's an old API that I'm using right now and therefore they refused to fix it. Switching to the new API would be quite some effort. So I implemented a workaround.

And that seems to cause the reported problem. I've created a patch. You can try if this helps:
https://testflight.apple.com/join/Ub8WcpcE

**Comment by dhermanns** [comment] 2021-08-01 09:58
Since I didn't get a reply, I would think that it is fixed now in the latest TestFlight...

**Closed by dhermanns** 2021-08-01 09:58 UTC

**Comment by Samhagberth** [comment] 2021-08-01 10:01
Yes it seems to be fixed have not seen the problem since,  thank you !


Sam Hagberth

**Comment by dhermanns** [comment] 2021-08-01 10:06
Great - thx Sam
