### ISSUE TITLE
NightGuard for Apple Watch and disabling all alerts

### ISSUE THREAD

**Issue by fromorbonia** [nightscout/nightguard#82] opened 2019-11-11 17:06 UTC
Hi, not sure if this is a bug or a feature request!

I have Nightguard installed to deliver current readings and the graph to an Apple Watch (on two separate phones / watch pairs). 
For a whole bunch of reasons we don't want any alarms at all from Nightguard (both on phone and watch). In looks as though the configuration for disabling this is working on the phones (although the low and high don't have an "off" we set them to max low and max high to minimise triggering). 
However, on the watch we seem to be getting random haptic feedback from Nightguard. Is there a way to ensure that Nightguard does not trigger any haptic feedback on the watch app?

Brilliant app though!

**Comment by dhermanns** [comment] 2019-11-12 20:11
Yes - right now, alarms can't be disabled completely. We already had the request to disable all alarms with just one button. I think that would be useful for others, too.

As you already mentioned, a workaround would be to set a very broad glucose range. And this should work both on the phone and the watch. I tried this and didn't get any haptic feedback on the watch. Do you get the haptic feedback from background updates, if the nightguard watchapp is closed? Do you see that the ranges get adjusted on the watch, when you modify the range on the watch?

**Comment by fromorbonia** [comment] 2019-12-12 15:34
@dhermanns  - thank you for replying, and I did see it soon after you posted, but then went on to try a number of things. I found something in my settings that wasn't helping and turned that off. So now my watch doesn't give me haptic feedback until the BG. 
My son who was using it, ended up switching back to Spike - so I haven't been able to do any "like for like testing". Might be able to do that over Christmas. 
Yes the ranges were in sync.

**Comment by dhermanns** [comment] 2019-12-12 16:23
What was that setting you changed?

**Comment by fromorbonia** [comment] 2020-01-14 16:08
@dhermanns - think I've found a cause for the multiple "alerts" on the Apple Watch. My son has an Apple Watch 2 (watchOS 5) and a phone with iOS12 , I have a later watch on watchOS 6 and a phone with iOS13.
On his watch, every time Night Guard restarts it triggers his watch to buzz. Night Guard regularly restarts throughout the day (which I assume is all around background apps and Apple), then end result is very confusing.
The buzz doesn't happen to me when Night Guard restarts (which I think it also does regularly)

**Comment by dhermanns** [comment] 2020-01-14 16:21
Nightguard checks if an alarm is necessary during background updates. I guess that is what you call a restart.

But it should give haptic feedback only if your values aren‘t in range or outdated. And that sounds to me like this is the way it works on your watchos 6 watch, right? Do you get alarms too if you open nightguard on your sons apple watch 2? I would expect that.

**Comment by fromorbonia** [comment] 2020-01-14 16:28
Yes - we get alarms on the watch when we open Nightguard, and it isn't already running on the phone.

**Comment by dhermanns** [comment] 2020-01-14 17:13
And are your values out of range? Speaking is the alarm correct?

**Comment by fromorbonia** [comment] 2020-01-16 20:41
No the values were not out of range.

**Comment by dhermanns** [comment] 2020-01-16 20:54
Does snoozing on the watch stop these alarms?

**Comment by Ba1ster** [comment] 2020-07-06 08:38
Hi can I ask a question pls.
I have Nightguard on my watch and iPhone. It works great on my iPhone, shows BG and graph.
On my watch (series 5) it only shows the BG levels and not the graph.
A message comes up saying can’t connect to the server..
I have refreshed the app to no gain.

Anyone help

**Comment by dhermanns** [comment] 2020-07-06 09:01
Hi Ba1ster! Does the watch displays the correct Backend when doing
Force-Press and then „Info“? If not - try to reenter your Backend Uri on
your Phone.

Cu,
Dirk

Ba1ster <notifications@github.com> schrieb am Mo. 6. Juli 2020 um 10:39:

**Comment by Ba1ster** [comment] 2020-07-06 09:08
Yes it displays it when I press info along with loads of updating.
When I launch the app it does say ‘loading BG data’ ( this can go on for some time) but the graph never loads and most of the time it comes with the message can’t connect to the server.
Thanks

**Comment by dhermanns** [comment] 2020-07-06 09:20
This is strange. You can leave me your Uri and I will have a look.

**Comment by Ba1ster** [comment] 2020-07-06 09:53
I use the one spike gave me which is http://127.0.0.1:1979
Thankyou

**Comment by dhermanns** [comment] 2020-07-06 10:10
This is just a local ip that I can‘t access from outside.

**Comment by Ba1ster** [comment] 2020-07-06 10:56
Any ideas what to do next? I’m clueless 
Thanks

**Comment by dhermanns** [comment] 2020-07-06 10:59
Do you plan to access your values from outside of your local lan? I could
have a look if you achieved that then.

**Comment by Ba1ster** [comment] 2020-07-06 11:16
No don’t think so. I view my BG readings on my iPhone and Apple Watch only. Accessing anywhere else is too complicated for me!

**Comment by dhermanns** [comment] 2020-07-06 11:28
And you would like access from your iPhone when you are at home only? How
do you host your nightscout backend?

**Comment by dhermanns** [comment] 2020-07-06 11:31
And your 127.0.0.1 IP won‘t even work there. You would need a valid Ip like 192.168.1.1. I would think that this is the root cause of your problem...

**Comment by Ba1ster** [comment] 2020-07-06 13:25
Mmm I will look into this. The Nightguard on my iPhone display the graph and readings fine and I use that IP address. When I look in to ingratiation section of the spike app it says to use the same ip on the watch.

So confused!

**Comment by dhermanns** [comment] 2020-07-06 15:55
Try to open your nightscout backend on a webrowser. If that works - it will
work on nightguard, too ;-)

**Comment by Ba1ster** [comment] 2020-07-06 22:21
Do u think it’s a good idea to restart the whole process again? I don’t really remember how I set it all up and go into thinks like u have mentioned and I’m at lost with it all

**Comment by dhermanns** [comment] 2020-07-07 05:00
Sounds reasonable

**Comment by Ba1ster** [comment] 2020-07-07 07:19
Sorry for so many questions, just have one more. Where exactly would u find the url in the Nightscout app?
Before I redo it all I thought I check as I really don’t know how to.
Thanks

**Comment by dhermanns** [comment] 2020-07-07 07:29
The Nightscout App is a website also known as cgm-remote-monitor. That is
what you typically install on your backend.

The default installation for it is on heroku.

Ba1ster <notifications@github.com> schrieb am Di. 7. Juli 2020 um 09:19:

**Comment by Pepustrong** [comment] 2020-07-19 20:38
Hi! I've a little problem with nightguard for apple watch series 2, in the screen that app iphone and watch show a message error, I supose for this I can't see in watch. ![image](https://user-images.githubusercontent.com/66573262/87884678-599d7400-ca10-11ea-92ec-32ecdd51e311.png)
Help me please😀 
Adeu! Bye! Ciao! 
Pura vida!

**Comment by dhermanns** [comment] 2020-07-19 20:57
Pepustrong <notifications@github.com> schrieb am So. 19. Juli 2020 um 22:39:

**Comment by dhermanns** [comment] 2020-07-19 20:59
Hi!

You can leave me your nightscout URI and I will have a look.

Pepustrong <notifications@github.com> schrieb am So. 19. Juli 2020 um 22:39:

**Comment by Pepustrong** [comment] 2020-07-19 23:44
Https://rocamejias.herokuapp.com

**Comment by dhermanns** [comment] 2020-07-20 05:15
Ah ok - looks like your site isn‘t free to read. So did you generate an Api
Token and did you append it to your Uri you entered in nightguard? Like
https://...?token=...

**Comment by Pepustrong** [comment] 2020-07-20 09:25
Hi, yes but I cant see

**Comment by dhermanns** [comment] 2020-07-20 09:50
Could you create a read token for me? I will try to reproduce it here...

**Comment by Pepustrong** [comment] 2020-07-26 21:23
Hi, I don't know token..

**Comment by dhermanns** [comment] 2020-07-27 07:07
You can create Api Tokens that you can pass to other people. So that you
can let them read your data, but don‘t have to let them know your  api
secret key.

Right now your site is secured, so nightguard can‘t read it without a
token. So you should generate one with your nightscout web application.

Cu,
Dirk

Pepustrong <notifications@github.com> schrieb am So. 26. Juli 2020 um 23:23:

**Comment by dhermanns** [comment] 2020-08-01 21:32
The feature for which this issue was created is already implemented. So I'm closing this now.

**Closed by dhermanns** 2020-08-01 21:32 UTC
Labels: enhancement
