### ISSUE TITLE
No graph, just current data

### ISSUE THREAD

**Issue by js-b-tech** [nightscout/nightguard#239] opened 2023-08-17 02:43 UTC
I deploy nightscout on nas, and use a customized port, generate a token for nightguard.
But there is no graph, just has current data. please help, thanks

![IMG_9928](https://github.com/nightscout/nightguard/assets/142403125/f76719f1-20cb-4ffb-a5f2-ff57e42a0248)

**Comment by dhermanns** [comment] 2023-08-17 04:21
Hi! Please do a search before opening a case. This should be a duplicate of: #228

**Comment by js-b-tech** [comment] 2023-08-17 04:55
> Hi! Please do a search before opening a case. This should be a duplicate of: #228

hello, thanks for replay. As I said, I have generate a token. no matter with careportal, readable role or with admin role, the nightguard can not show any graph. but the same url and same token can access in any browser.

**Comment by dhermanns** [comment] 2023-08-17 05:37
Ok. You can send me your URI with your token to issue239.hermanns@spamgourmet.com.

**Comment by dhermanns** [comment] 2023-08-17 05:43
Thanks. Works on my machine ;). What is your nightguard version?

**Comment by js-b-tech** [comment] 2023-08-17 06:22
my nightguard version is v3.8.0.828
my ios version is 16.6
my device is iPhone 12 Pro Max
my nightscount version is 14.2.6


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nightscout/nightguard"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月17日(星期四) 中午1:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nightscout/nightguard] No graph, just current data (Issue #239)





 
Thanks. Works on my machine ;). What is your nightguard version?

**Comment by dhermanns** [comment] 2023-08-17 19:55
Looks like your sgv values can't be converted using floats. How do you capture your bg-values? Please try the upcoming TestFlight build 381. This should fix your issue.

**Comment by dhermanns** [comment] 2023-08-17 19:57
Here is the TestFlight Link: https://testflight.apple.com/join/Ub8WcpcE

**Comment by js-b-tech** [comment] 2023-08-18 06:35
> Looks like your sgv values can't be converted using floats. How do you capture your bg-values? Please try the upcoming TestFlight build 381. This should fix your issue.

it's worked, thank you !

**Closed** 2023-08-31 16:42 UTC
