### ISSUE TITLE
Nightguard App - Constant high BG alarms

### ISSUE THREAD

**Issue by MikeLee1762** [nightscout/nightguard#125] opened 2020-10-09 11:08 UTC
High alarm slider not working. Constant high BG alarms no matter what BG level is since latest update. Have deleted app several times and re-installed makes no difference

**Comment by dhermanns** [comment] 2020-10-09 12:11
Hi! Are you using mmol?

**Comment by MikeLee1762** [comment] 2020-10-09 12:28
Hi
Yes I am using mmol.

**Comment by dhermanns** [comment] 2020-10-09 13:37
Can you elaborate a bit where you get these alerts? I can‘t reproduce this
even when using mmol...

**Comment by aaronkloos2020** [comment] 2020-10-09 13:53
I am having same issue saying high when in the 5,s

**Comment by makotila** [comment] 2020-10-09 14:09
I have same problem, using mmol. Also delta value is always wrong (maybe I should create new issue), it's about 1/10 from  expected value

**Comment by aaronkloos2020** [comment] 2020-10-09 14:11
> Can you elaborate a bit where you get these alerts? I can‘t reproduce this even when using mmol...

Pls can you fix this issue?

**Comment by aaronkloos2020** [comment] 2020-10-09 14:12
I really rely on this app constantly saying high bg even when low

**Comment by dhermanns** [comment] 2020-10-09 14:15
I can reproduce this now. So I will be able to create a fix for this soon.

Would be good to have you as a Beta Tester on TestFlight - if not already.

**Comment by MikeLee1762** [comment] 2020-10-09 14:22
Hi
I have my low alarm set at 5.5 and my high alarm set at 10.5. When my BG drops below 5.5 I get an alarm but it says ‘high BG alarm’, should say ‘low BG alarm’. 
When my BG goes above about 6.0 I get a ‘high BG alarm’. 
Using iphoneXR. 
Updated app prior to IOS14 install. Following problems have updated to IOS14 but no change. 
I have also noticed that the difference between your last BG reading at top of app only ever says + or - 0

Thanks

**Comment by MikeLee1762** [comment] 2020-10-09 14:27
I have test flight installed on my phone but would not know how to install your Beta version. Happy to help

**Comment by dhermanns** [comment] 2020-10-09 15:09
The bgdelta value seems to be a bug in your nightscout backend. If I have a look at the pebble http-endpoint, it simply return bgdelta="0". And that is what is displayed. But this is really a different issue. Just for your information. You should open a case for it in the cgm-remote-monitor project.

**Comment by MikeLee1762** [comment] 2020-10-09 15:14
Thanks 👍

**Comment by aaronkloos2020** [comment] 2020-10-09 15:34
> I can reproduce this now. So I will be able to create a fix for this soon. Would be good to have you as a Beta Tester on TestFlight - if not already.

**Comment by aaronkloos2020** [comment] 2020-10-09 15:36
Great a fix pls as I love this app.  What is test flight?

**Comment by MikeLee1762** [comment] 2020-10-09 15:40
If you let me know how I down load via test flight will be happy to help. Test flight already on phone

**Comment by dhermanns** [comment] 2020-10-09 16:23
I'm not quite sure whether I really was able to reproduce it completely. But you can try the latest V3.1.2 in a couple of minutes:
https://testflight.apple.com/join/Ub8WcpcE

For all having problems with the mmol-Delta Values being +-0: Try updating your nightscout backend to the latest version. There seems to be already a fix for this.

**Comment by MikeLee1762** [comment] 2020-10-09 19:41
Now testing will let you know how it goes

**Comment by ByteMarks74** [comment] 2020-10-09 20:50
We are still having the issue with high alarms for in range numbers. Any idea when it will be fixed. Thanks for your hard work.

**Comment by dom209** [comment] 2020-10-09 20:52
I have been having the same issue with false high alarms since the update. Updating to 3.1.1(615) through Test Flight seems to have resolved it.

**Comment by dhermanns** [comment] 2020-10-09 20:56
V3.1.2 is already waiting for apples approval. But seems to take some time
today...

It should definitely fix an high alert error. But not sure if this is
exactly what you are experiencing.

Should be normally ready in TestFlight in the next minutes/hours.

>

**Comment by MikeLee1762** [comment] 2020-10-09 21:24
Still having problems with high alarms.

**Comment by andruhamessi** [comment] 2020-10-09 22:43
> For all having problems with the mmol-Delta Values being +-0: Try updating your nightscout backend to the latest version. There seems to be already a fix for this.

I updated my Nightscout backend to the last 14.0.6 version. It didn’t solve the mmol-Delta problem. Nightguard 3.0.2.593 show delta right. Nightguard 3.1.1.615 shows delta -+0. All other apps that use the same Nightscout url also show delta right.

**Comment by dhermanns** [comment] 2020-10-10 03:33
I‘m using the pebble api endpoint and then it seems still broken with 14.0.6 for a mmol backend. But we should discuss this in another issue.

Regarding the high alarms: How do you reproduce it with 3.1.2?

**Comment by dhermanns** [comment] 2020-10-10 03:45
You could leave me your URL at url.hermanns@spamgourmet.com. Maybe it‘s something special with the Nightscout backend version.

**Comment by dhermanns** [comment] 2020-10-10 03:57
For the bgdelta issue I filed a bug report here:

https://github.com/nightscout/cgm-remote-monitor/issues/6220

In the earlier Nightguard Version I worked around that issue, but it leads to other problems. So it should be fixed at its root.

**Comment by dhermanns** [comment] 2020-10-10 07:00
V3.1.2 is released now. Let me know how you reproduce any more unexpected high alarms. I tried to get unexpected alarms with a mmol backend last night, but I’m not able to with V3.1.2.618.

Hope it solves it for you all, too.

**Comment by dhermanns** [comment] 2020-10-10 14:55
Upcoming TestFlight V3.1.3 should workaround the nightscout bgdelta mmol bug. Closing here. Let me know if there is still a problem with highbgs and the current versions...

**Closed by dhermanns** 2020-10-10 14:55 UTC
Labels: bug

**Comment by MikeLee1762** [comment] 2020-10-10 15:28
8hrs of testing and alarms all ok
Thanks

Mike Lee

**Comment by dhermanns** [comment] 2020-10-10 16:10
Great - thx all for your Feedback!

**Comment by makotila** [comment] 2020-10-10 16:38
Works great now, thanks!

**Comment by aaronkloos2020** [comment] 2020-10-11 18:39
> V3.1.2 is released now. Let me know how you reproduce any more unexpected high alarms. I tried to get unexpected alarms with a mmol backend last night, but I’m not able to with V3.1.2.618.
> 
> Hope it solves it for you all, too.

How do I get the latest release to fix problem

**Comment by MikeLee1762** [comment] 2020-10-11 18:41
You can download from the App Store
