### ISSUE TITLE
Feature requirements: Can you support mmol/L unit in this app

### ISSUE THREAD

**Issue by jizhongwen** [nightscout/nightguard#38] opened 2018-04-19 08:54 UTC
Thank you for developing this app. It is very useful. Can you  support mmol/L unit in this app

**Comment by florianpreknya** [comment] 2018-04-22 08:47
We're glad you like the app, thanks for appreciation! :)
Currently the app will display the current bg value in mmol if your nightscout server DISPLAY_UNITS variable is set to mmol. The alarms and the graph have no support yet, but will have pretty soon. Stay tuned!

**Comment by dhermanns** [comment] 2018-04-22 09:59
I‘m not using mmol myself but I‘m pretty sure that graph and alarms work if
you configure DISPLAY_UNITS correctly.
Florian Preknya <notifications@github.com> schrieb am So. 22. Apr. 2018 um
10:47:

**Comment by dhermanns** [comment] 2018-04-22 10:54
![simulator screen shot - iphone 8 - 2018-04-22 at 12 51 09](https://user-images.githubusercontent.com/3207317/39094194-28a9dc9a-462c-11e8-960c-175834ef55a0.png)

![simulator screen shot - iphone 8 - 2018-04-22 at 12 51 01](https://user-images.githubusercontent.com/3207317/39094199-400ba29c-462c-11e8-88dc-fd5b2d686313.png)

**Comment by dhermanns** [comment] 2018-04-22 10:55
We already had a few users who managed to work with wrong DISPLAY_UNITS. Maybe we should have the ability to set it in our app. So it's easier for most users to correct the wrong server settings.

**Comment by florianpreknya** [comment] 2018-04-28 06:43
Yes, you're right @dhermanns. It's strange that the first run didn't show the mmol units on graph and alarms screen. Then it worked perfectly.

**Comment by jizhongwen** [comment] 2018-05-24 13:52
Thank you for your answer, I got it. It should be related to the default Display units in the NS server. I think we need to set it in your app

**Comment by dhermanns** [comment] 2019-04-26 18:21
I think that should work fine now. What we recently had was a problem due to whitespaces in the nightscout mmol configuration. We should see whether we could be more generous in parsing that.

**Comment by mfcr06** [comment] 2019-06-04 06:47
HI,I know this thread is old,  I have just set up nightscout with Nightguard and even tough my values are set at mmol, what is pulling through to my iPhone and Apple Watch is mgdl.  Does anyone have any suggestions?

**Comment by dhermanns** [comment] 2019-06-04 06:59
Hi! You could send me your Uri and I will have a look. The problem from the original poster was whitespaces in the heroku mmol configuration. Did you check that?

**Comment by mfcr06** [comment] 2019-06-04 07:05
Yes, I did and from what I can see it is mmol.  I'd love to send you though my URI but I have no idea what that is........

**Comment by dhermanns** [comment] 2019-06-04 07:14
The link to your nightscout backend. The original poster had mmol
configured, too.

But it turned out that it was something like
 „ mmol “

**Comment by mfcr06** [comment] 2019-06-04 07:23
OK, I get what you mean......through here or PM?

**Comment by dhermanns** [comment] 2019-06-04 07:32
As you like

**Comment by mfcr06** [comment] 2019-06-04 07:54
Hang on, I must'nt have saved it when I changed it on my iPhone for the 50th time..........now my iPhone is in mmol but my Apple Watch is still in mgdl.

**Comment by mfcr06** [comment] 2019-06-04 08:35
Iphone


Apple watch


https://fionaryan1973.herokuapp.com

I have deleted the complication from the watch and reinstalled but it is stuck in mgdl.

Any advice would be greatly appreciated.

Thanks, 
Fiona Ryan

**Comment by florianpreknya** [comment] 2019-06-04 09:10
Hey Fiona,

I think the problem is that you Units are set in Heroku as "mmol/L". That's the request: https://fionaryan1973.herokuapp.com/api/v1/status.json

The possible values are "mg/dl" and "mmol" according to Nightscout doc: https://elements.heroku.com/buttons/nightscout/cgm-remote-monitor.

So, change the DISPLAY_UNITS variable in Heroku from "mmol/L" in "mmol" and it should work.

**Comment by mfcr06** [comment] 2019-06-04 11:15
Thank you. All sorted now. I am Nightscouting. Very much appreciated.

Thanks, 
Fiona Ryan

**Comment by bjornoleh** [comment] 2020-07-21 09:54
Hi, after a couple of months using nightguard displaying mmol values on iPhone SE gen1, suddenly I can only see mg/dL values. 

Have changed the DISPLAY_UNITS to 'mmol' (was mmol/L, and was working before), reinstalled app, and restarted phone. Did anything change in the last days? 

We changed the G6 transmitter yesterday, works fine in G6 app and Loop, so probably unrelated?

Thanks!

**Comment by dhermanns** [comment] 2020-07-21 10:35
Hi! Do you have any whitespaces in your DISPLAY_UNITS?

bjornoleh <notifications@github.com> schrieb am Di. 21. Juli 2020 um 11:54:

**Comment by bjornoleh** [comment] 2020-07-21 10:53
Thanks for the quick reply.  I checked,  and there are/were no blanks.  And it did work even when entered as 'mmol/L'

**Comment by bjornoleh** [comment] 2020-07-21 11:01
Hm, but I did deploy the "Fixes" branch of Nightscout (merged it with my forked Dev). So probably something there. We also noticed now that the delta value is missing in a fitbit app (Glance).

**Comment by dhermanns** [comment] 2020-07-21 11:08
What do you get when calling 'http://<yournightscoutbackend>/api/v1/status.json' in your browser?

**Comment by bjornoleh** [comment] 2020-07-21 11:11
Not available? (On Android phone, Chrome)

Sorry, Norwegian:

Dette nettstedet er ikke tilgjengelig
Fant ikke IP-adressen til tjeneren for api.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by bjornoleh** [comment] 2020-07-21 11:18
Sorry, I misunderstood. Two sec, I'll paste it here.

**Comment by bjornoleh** [comment] 2020-07-21 11:19
{"status":"ok","name":"nightscout","version":"13.1.0","serverTime":"2020-07-21T11:17:03.762Z","serverTimeEpoch":1595330223762,"apiEnabled":true,"careportalEnabled":true,"boluscalcEnabled":true,"settings":{"units":"mmol","timeFormat":24,"nightMode":false,"editMode":true,"showRawbg":"never","customTitle":"Endre","theme":"colors","alarmUrgentHigh":false,"alarmUrgentHighMins":[30,60,90,120],"alarmHigh":false,"alarmHighMins":[30,60,90,120],"alarmLow":false,"alarmLowMins":[15,30,45,60],"alarmUrgentLow":false,"alarmUrgentLowMins":[15,30,45],"alarmUrgentMins":[30,60,90,120],"alarmWarnMins":[30,60,90,120],"alarmTimeagoWarn":false,"alarmTimeagoWarnMins":"15","alarmTimeagoUrgent":false,"alarmTimeagoUrgentMins":"15","alarmPumpBatteryLow":false,"language":"nb","scaleY":"linear","showPlugins":"iob cob careportal loop basal override bwp boluscalc delta direction upbat","showForecast":"loop","focusHours":3,"heartbeat":60,"baseURL":"","authDefaultRoles":"readable","thresholds":{"bgHigh":252,"bgTargetTop":180,"bgTargetBottom":72,"bgLow":67},"insecureUseHttp":false,"secureHstsHeader":true,"secureHstsHeaderIncludeSubdomains":false,"secureHstsHeaderPreload":false,"secureCsp":false,"deNormalizeDates":false,"showClockDelta":true,"showClockLastTime":true,"bolusRenderOver":1,"frameUrl1":"https://nsnh.herokuapp.com/clock/by10-tm20-nl-sg30-dt20-nl-ag15","frameUrl2":"https://xxxx.herokuapp.com/clock/by10-tm20-nl-sg30-dt20-nl-ag15","frameUrl3":"","frameUrl4":"","frameUrl5":"","frameUrl6":"","frameUrl7":"","frameUrl8":"","frameName1":"","frameName2":"","frameName3":"","frameName4":"","frameName5":"","frameName6":"","frameName7":"","frameName8":"","DEFAULT_FEATURES":["bgnow","delta","direction","timeago","devicestatus","upbat","errorcodes","profile","dbsize"],"alarmTypes":["predict"],"enable":["bridge","loop","pump","iob","cob","basal","careportal","sage","cage","openaps","override","cors","bwp","rawbg","boluscalc","treatmentnotify","bgnow","delta","direction","timeago","devicestatus","upbat","errorcodes","profile","dbsize","ar2"]},"extendedSettings":{"pump":{"retroFields":"battery reservoir clock status","fields":"battery reservoir clock status"},"loop":{"enableAlerts":false,"warn":20,"urgent":60},"sage":{"warn":236,"info":216,"urgent":238},"basal":{"render":"icicle"},"devicestatus":{"advanced":true,"days":1}},"authorized":null}

**Comment by dhermanns** [comment] 2020-07-21 14:20
Have I look at your endpoint https://yyyy.herokuapp.com/pebble. This is what is used to display the current values.
In your case it returns a mgdl sgv. So there seems to be something misconfigured in your backend.

**Comment by dhermanns** [comment] 2020-07-21 14:36
Ah ok - I found a way to enforce mmol for the pebble endpoint no matter what is misconfigured on your backend. Your settings clearly denotes "mmol". So I build a new nightguard version that enforces the settings for the pebble endpoint by adding /pebble?units=mmol and that seems to work for your backend fine now.

If you like I can enter your email to the list of TestFlight beta users.

**Comment by bjornoleh** [comment] 2020-07-21 15:19
Ok, great. Did I mess something up trying to use the NS Fixes branch? 

Thanks, please do add to testflight. Can I also build Nightguard like with Loop using Workspace?

**Comment by dhermanns** [comment] 2020-07-21 15:31
V2.9.0 should work for you. You can add yourself to the testing group here:
https://testflight.apple.com/join/Ub8WcpcE

Apple should enable public testing for this version soon...

And yes - you can build nightguard on your own.

**Comment by dhermanns** [comment] 2020-07-22 11:17
V2.9.0 is available for public testing now. Let me know if it is working for you now...

**Comment by bjornoleh** [comment] 2020-07-22 12:38
Thanks! Will try, but where do I find this public testing version? I cant see it in App store. And Testflight is not accepting more testers according to the previous link.

**Comment by dhermanns** [comment] 2020-07-22 12:44
Hm - this one should still be active: 
https://testflight.apple.com/join/Ub8WcpcE

Please try again - I've increased the number of allowed users.

**Comment by bjornoleh** [comment] 2020-07-22 12:46
Yes, I noticed now that I could enroll. I have installed 2.9.0 via Testflight now, and its working both on iPhone and watch. Thanks!

**Comment by dhermanns** [comment] 2020-07-22 12:58
Great 👍

**Comment by bjornoleh** [comment] 2020-07-26 12:39
Hi, the 2.9.0 Testflight distribution is mostly working fine, but I have had three crashes. I think i sent an error report via Testflight,  but did not enter my email or add any notes. I have no relevant context to add to the crash.

**Comment by dhermanns** [comment] 2020-07-26 15:52
Did you get this error when the app is in background? This is a known bug
which you only see when in testflight mode.

Hard to tackle down :-/

**Comment by bjornoleh** [comment] 2020-07-26 16:09
Ok, that's probably it. Thanks.

søn. 26. jul. 2020, 17:52 skrev dhermanns <notifications@github.com>:

**Closed** 2020-08-01 21:35 UTC
Labels: enhancement

**Comment by bjornoleh** [comment] 2020-09-25 14:41
> Have I look at your endpoint https://yyyy.herokuapp.com/pebble. This is what is used to display the current values.
> In your case it returns a mgdl sgv. So there seems to be something misconfigured in your backend.

Hi @dhermanns , I know this issue is closed, but it seems there is a change in NS Dev now that might affect or improve the detection of mmol/mgdl units.

https://github.com/nightscout/cgm-remote-monitor/commit/07eee47257486896f237c64c6f0aa7ecc97b66ed

**Comment by dhermanns** [comment] 2020-09-25 14:51
Interesting- can you elaborate on this?

**Comment by bjornoleh** [comment] 2020-09-25 15:01
It's  just a guess on my part, as there was some issue with  /pebble when we looked into this a while back. I just noticed the mentioned commit, which seems related. But I don't actually understand the code...
