### ISSUE TITLE
WatchOS 9 complication

### ISSUE THREAD

**Issue by KlaidasV** [nightscout/nightguard#200] opened 2022-09-13 19:07 UTC
Hello!

after upgrading apple watch to OS 9 - i am unable to see data from complications (there is no more ability to see info on main screen like in picture below:

![DA4FE1D1-E726-45AF-ADF6-E80136D444B0](https://user-images.githubusercontent.com/98658915/189988545-080f171d-ce3f-4d9e-b58c-58d48f825049.jpeg)

**Comment by dhermanns** [comment] 2022-09-13 19:34
Thanks for the feedback. I'm still on watchos8 ;-).

But will update now and have a look.

**Comment by dhermanns** [comment] 2022-09-14 05:24
Can reproduce this. Workaround is to switch to another complication type. E.g. circular is still working fine.

Crazy how many things apple breaks after major updates.

**Comment by KlaidasV** [comment] 2022-09-14 05:37
Yeah currently i am using other type of complication, but the previous one was more comfortable to see the trend :) Will you manage to fix this? Thanks a lot!!! Klaidas Viskontas+370 636 07546On 2022-09-14, at 08:25, dhermanns ***@***.***> wrote:﻿
Can reproduce this. Workaround is to switch to another complication type. E.g. circular is still working fine.
Crazy how many things apple breaks after major updates.

**Comment by dhermanns** [comment] 2022-09-14 05:39
Yes - will be fixed with the upcoming version.

**Comment by dhermanns** [comment] 2022-09-18 18:30
Had a look - but everything looks fine on my side. Seems to be a bug in iOS 16. 
Apple deprecated a lot of stuff there. Maybe we should switch to SwiftUI Views.

So could be that an upcoming iOS 16.x fixes it. Otherwise I will see how I could workaround this.

**Closed** 2022-12-07 11:52 UTC
