### ISSUE TITLE
Wrong delta (change speed) 

### ISSUE THREAD

**Issue by Korzina-k** [nightscout/nightguard#164] opened 2021-10-16 11:13 UTC
the changes speed is wrong. Previous indication is 5.4, current 5.7, delta is 5 (should be 0.3 like it is  in Nightscout connected to the same server)
![ED4AFC13-AAC5-4285-9333-8FE08819CE4C](https://user-images.githubusercontent.com/92630645/137585105-16975d5a-ae19-467d-a09b-7ed3546fa77b.png)
![09A511CD-9F46-412A-850C-964BA3A4D74A](https://user-images.githubusercontent.com/92630645/137585108-5a419e26-1124-4f22-b2eb-23c5559d6cd1.png)

**Comment by dhermanns** [comment] 2021-10-17 13:58
This is a duplicate of #163 .

**Comment by dhermanns** [comment] 2021-10-17 20:47
I replaced the old and buggy nightscout API with the newer V2 one. Can you have a look whether this is fine now for you?
The TestFlight will be available soon here:

https://testflight.apple.com/join/Ub8WcpcE

It will have V3.6.1 label.

**Closed as completed** 2021-10-20 16:02 UTC
