### ISSUE TITLE
Bg on App badge even when disabled

### ISSUE THREAD

**Issue by OpossumGit** [nightscout/nightguard#77] opened 2019-07-12 19:08 UTC
I have enabled app badge and was unhappy how it is inaccurate and late. Then I disabled it but badge is still there and still showing wrong info. 
I am on mmol units if that matters

**Comment by dhermanns** [comment] 2019-07-12 19:59
Hi!

I just tested it and it vanishes after disabling the badge. The update is
as accurate as apple allows us to do background updates if the app is in
background.

Have you tried deinstallieren/reinstalling the App?

**Comment by OpossumGit** [comment] 2019-07-12 20:36
I have reenabled it, then disabled it. It disappeared for some time and then reappeared. 

I will uninstall an reinstall now and then enable it then disable it to see what happens

**Comment by dhermanns** [comment] 2019-07-12 20:39
Ah ok - then I will see whether it will reappear after some time. Maybe
that’s the problem.

**Comment by OpossumGit** [comment] 2019-07-13 06:39
After reinstallation and turning it in, still waiting for badge to appear. 
There are some serious issues with this feature on my phone :(

**Comment by dhermanns** [comment] 2019-07-13 08:52
I think after the background update is done, the badge reappears for me, too.

@florianpreknya can you have a look.

I‘m struggling for 2 month now with apple support to get the app watch part migrated to the new developer account. So I won‘t be able to release a fix until apple helps :-/

**Comment by florianpreknya** [comment] 2019-07-13 20:19
I’ll take a look as soon as I’ll return from m holiday. And yes, badge updates and notifications are not so reliable when the app is in background. The app requests background time often, but it receives it not so often from iOS. A more reliable solution should be based on remote notifications, but a server is needed for that (or a third party notification service - like Spike does).

**Comment by makotila** [comment] 2020-02-20 15:29
I'm suffering from the same problem with iPhone SE 13.3.1. Not big problem but I would like that false value from the badge vanished by setting "Show BG on App Badge" off

**Comment by dhermanns** [comment] 2020-02-23 09:32
@florianpreknya : Did you already had a look?

**Comment by dhermanns** [comment] 2020-05-04 20:30
I had a look and it seems ok for me. Tried to reproduce it once more. But the badge seems now to be disabled correctly. @OpossumGit, @makotila : is this still an issue? How could you reproduce it?

**Comment by OpossumGit** [comment] 2020-05-04 20:42
Currently app badge setting is on but I don’t see the badge. Tried to turn it off and back on but it is not showing.

**Comment by dhermanns** [comment] 2020-05-04 20:55
What‘s your device and your current nightguard version?

**Comment by OpossumGit** [comment] 2020-05-04 20:59
iPhone 7 13.4.1. Nightguard v2.4.7.512

**Comment by dhermanns** [comment] 2020-05-10 16:34
Than your behavior is the opposite of the ticket? You have enabled the feature in nightguard but didn't see the bg on the app badge, right? Did you allow nightguard to show the badge in your iPhone settings? This has to be turned on, otherwise you won't see the badge, no matter what you have defined in nightguard.

**Comment by OpossumGit** [comment] 2020-05-10 19:06
Yes. Now it is opposite. Earlier it was shown but I was unable to remove it. Now I am unable to show it again. 

The same goes for my wife’s iPhone 8.

**Comment by dhermanns** [comment] 2020-05-10 20:07
Did you try to check your iOS Notification Settings for nightguard?

**Comment by OpossumGit** [comment] 2020-05-10 20:59
Background app refresh and badges are both on

**Comment by dhermanns** [comment] 2020-05-11 05:48
Not reproducible here. You can send me your URI to my Twitter handle if you like @h3rmanns. Maybe it‘s a setting with your backend.

**Comment by derivadow** [comment] 2020-09-08 13:42
I have experienced this bug but can't work out the specific scenario to recreate it. 

When it happens with me there is also a mismatch between the actual BG (when you open the app) and the value displayed on the badge + it happens overnight and coz grrr I'm having nighttime hypos at the moment I wondered if it was related to alarms, overriding the iOS sleep function or snooze but can't recreate the right conditions...

**Comment by derivadow** [comment] 2020-09-10 11:59
Ok I *think* I can replicate this. 

It happens when an alarm and iOS notification is triggered.

**Comment by dhermanns** [comment] 2020-09-12 10:35
Thinks for these insights. I will try to reproduce it this way!

**Comment by dhermanns** [comment] 2020-10-04 11:02
Yes - seems to be really the case if a notification was triggered. There was a condition missing.
Added it. But I think the problem could be, that when generating the notification, the device could be locked.

Looks like apple decided that the code has now access to the UserDefaults in this situation. Therefore we are not
able to get the Information whether the user decided to have the glucose level on the app badge.

I'm trying to force the code to run on the main thread now. But not sure if this could work...

**Comment by dhermanns** [comment] 2020-10-08 06:14
Should be fixed with V3.1.0 now.

**Closed by dhermanns** 2020-10-08 06:14 UTC
Labels: bug
