### ISSUE TITLE
nightguard 2.7.2 is closing after a few minutes up.

### ISSUE THREAD

**Issue by marcusfpereira** [nightscout/nightguard#83] opened 2019-12-16 02:41 UTC
Aftter the recent update of Nightguard to verstion 2.7.2 the app is closing a few minutes after at the fist update.

I am using IPhone X with iOS 13.3.

**Comment by dhermanns** [comment] 2019-12-16 06:48
Hi! Works fine on my XS for weeks. But I was on iOS13.2. Updated today - but at least works till now without a problem. Do you have developer feedback enabled on your phone, so that I can get your crash reports?

**Comment by marcusfpereira** [comment] 2019-12-16 12:54
I've just sent a report just after a crash. I don't know if it was the correct way to send it since it was the first time I've used the Developer Feedback app.
I've tested on some other devices:
IPhone 6, IPhone SE with iOS 13.3 also crashed but it took a lot more time then on the IPhone X. On IPhone X it takes less then 10 minutes to crash, on the other devices it took more then 20 minutes.
IPhone 5S with iOS 12.4 no crashes.

**Comment by dhermanns** [comment] 2019-12-16 13:07
Hi Marcus!

You can send me your backend URL and I can have a look whether the error is
related to your setup.

I will have a look at the crash reports, too.

Cu,
Dirk

**Comment by marcusfpereira** [comment] 2019-12-16 13:10
The nightscout url is https://becgm.herokuapp.com


Em seg., 16 de dez. de 2019 às 10:07, dhermanns <notifications@github.com>
escreveu:

**Comment by florianpreknya** [comment] 2019-12-17 08:09
Yes, I can also confirm the app crashes. I have experienced it on both of my phones,  iPhone XS (iOS 13.3) and iPhone 6S (iOS 13.1.3).

I'll investigate the problem in the following days. The problem seems to be related to "Dim screen when idle" option, because if I turn it off, it doesn't crash anymore. Could you also confirm this, @marcusfpereira?

**Comment by dhermanns** [comment] 2019-12-17 08:32
Ah - excellent. That would have been my next question: What are your
settings. Since my app runs fine even when using the mentioned backend.

**Comment by dhermanns** [comment] 2019-12-17 08:35
Can reproduce marcus problem now, too. Workaround is to set „Dim Screen when Idle“ to „Never“ (what was my setting).

**Comment by marcusfpereira** [comment] 2019-12-17 11:47
Confirmed. When "Dim Screen when Iddle" is set to "Never" there is no more crashes!

**Comment by dhermanns** [comment] 2019-12-22 20:59
This is fixed with V2.7.3. It is already waiting for a review from apple.

**Closed by dhermanns** 2019-12-22 20:59 UTC
